
### posts POST http://localhost:8000/api/posts Content-Type: application/json



POST http://localhost:8000/api/posts
Content-Type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6InBydWViYTQiLCJ1c2VybmFtZSI6InBydWViYTQiLCJlbWFpbCI6InBydWViYUBnbWFpbC5jb200IiwiaWF0IjoxNjQ4NTY3NDc0LCJleHAiOjE2NTExNTk0NzR9.Kb_wAzE8ye9y8ARnCoUqZBhLXBd02_mz5BOx10FshkI


{
    "userid": "2",
    "title": "title",
    "description": "food",
    "image": "https://media.istockphoto.com/photos/selection-of-american-food-picture-id931308812?k=20&m=931308812&s=612x612&w=0&h=Tudia4RSCvfpWZhli0ehScrzeCtbwvTqB9BZaCta_qA=",
    "video": "videoUrl",
    "category": 2

}


### posts GET http://localhost:8000/api/posts Content-Type: application/json



GET http://localhost:8000/api/posts


### post to id GET http://localhost:8000/api/posts Content-Type: application/json



GET http://localhost:8000/api/posts/2


### all user posts to id GET http://localhost:8000/api/posts Content-Type: application/json



GET http://localhost:8000/api/posts/userPosts/3



### edit user put http://localhost:8000/api/users/profile Content-Type: application/json

PUT http://localhost:8000/api/posts/edit/2
Content-Type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6InBydWViYTQiLCJ1c2VybmFtZSI6InBydWViYTQiLCJlbWFpbCI6InBydWViYUBnbWFpbC5jb200IiwiaWF0IjoxNjQ4NTY3NDc0LCJleHAiOjE2NTExNTk0NzR9.Kb_wAzE8ye9y8ARnCoUqZBhLXBd02_mz5BOx10FshkI

{
    "description": "super ricooo"

}

### post  DELETE http://localhost:8000/api/users/delete/:id 



DELETE http://localhost:8000/api/posts/delete/6
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6InBydWViYTQiLCJ1c2VybmFtZSI6InBydWViYTQiLCJlbWFpbCI6InBydWViYUBnbWFpbC5jb200IiwiaWF0IjoxNjQ4NTY3NDc0LCJleHAiOjE2NTExNTk0NzR9.Kb_wAzE8ye9y8ARnCoUqZBhLXBd02_mz5BOx10FshkI



### url remota


### posts POST http://api-gout.herokuapp.com/api/posts Content-Type: application/json



POST http://api-gout.herokuapp.com/api/posts
Content-Type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6InBydWViYTQiLCJ1c2VybmFtZSI6InBydWViYTQiLCJlbWFpbCI6InBydWViYUBnbWFpbC5jb200IiwiaWF0IjoxNjQ4NTY3NDc0LCJleHAiOjE2NTExNTk0NzR9.Kb_wAzE8ye9y8ARnCoUqZBhLXBd02_mz5BOx10FshkI


{
    "userid": "6",
    "title": "Pizza italiana",
    "description": "Deliciosa pizza",
    "image": "https://www.guidingtech.com/wp-content/uploads/HD-Mouth-Watering-Food-Wallpapers-for-Desktop-12_4d470f76dc99e18ad75087b1b8410ea9.jpg",
    "video": "videoUrl",
    "category": 5

}


### posts GET http://api-gout.herokuapp.com/api/posts Content-Type: application/json



GET http://api-gout.herokuapp.com/api/posts


### post to id GET http://api-gout.herokuapp.com/api/posts Content-Type: application/json



GET http://api-gout.herokuapp.com/api/posts/50



### all user posts to id GET http://api-gout.herokuapp.com/api/posts Content-Type: application/json



GET http://api-gout.herokuapp.com/api/posts/userPosts/3



### edit user put http://api-gout.herokuapp.com/api/users/profile Content-Type: application/json

PUT http://api-gout.herokuapp.com/api/posts/edit/3
Content-Type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6InBydWViYTQiLCJ1c2VybmFtZSI6InBydWViYTQiLCJlbWFpbCI6InBydWViYUBnbWFpbC5jb200IiwiaWF0IjoxNjQ4NTY3NDc0LCJleHAiOjE2NTExNTk0NzR9.Kb_wAzE8ye9y8ARnCoUqZBhLXBd02_mz5BOx10FshkI

{
    "description": "esta es la receta de locro"

}

### post  DELETE http://api-gout.herokuapp.com/api/users/delete/:id 



DELETE http://api-gout.herokuapp.com/api/posts/delete/4