### users GET http://localhost:8000/api/users Content-Type: application/json



GET http://localhost:8000/api/users



### users/id GET http://localhost:8000/api/users/:id Content-Type: application/json



GET http://localhost:8000/api/users/3



### register POST http://localhost:8000/api/users/register Content-Type: application/json



POST http://localhost:8000/api/users/register 
Content-Type: application/json

{
  "username": "prueba4",
  "email": "prueba@gmail.com4",
  "password": "123456789",
  "nickname": "prueba4"
}



### Login POST http://localhost:8000/api/users/login Content-Type: application/json


POST http://localhost:8000/api/users/login 
Content-Type: application/json

{
  "email": "prueba@gmail.com4",
  "password": "123456789"
}

### edit profile put http://localhost:8000/api/users/profile Content-Type: application/json



PUT http://localhost:8000/api/users/profile 
Content-Type: application/json
# Authorization: `Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6InBydWViYSIsInVzZXJuYW1lIjoicHJ1ZWJhIiwiZW1haWwiOiJwcnVlYmFAZ21haWwuY29tIiwiaWF0IjoxNjQ1NTQxODkyLCJleHAiOjE2NDgxMzM4OTJ9.9IKB2VQWTSThpOKIrwFAFkS-k_g83sKQlwGg0ijICfo`

{
  "id": "7",
  "username": "update prueba",
  "email": "updateprueba@gmail.com",
  "password": "938472829",
  "nickname": " updateprueba",
   "avatar": "https://picsum.photos/id/1/200/300",
  "backgroundImage": null
}


### edit user put http://localhost:8000/api/users/profile Content-Type: application/json

PUT http://localhost:8000/api/users/edit/7
Content-Type: application/json
# Authorization: `Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6InBydWViYSIsInVzZXJuYW1lIjoicHJ1ZWJhIiwiZW1haWwiOiJwcnVlYmFAZ21haWwuY29tIiwiaWF0IjoxNjQ1NTQxODkyLCJleHAiOjE2NDgxMzM4OTJ9.9IKB2VQWTSThpOKIrwFAFkS-k_g83sKQlwGg0ijICfo`

{
  "username": "update prueba",
  "email": "updateprueba@gmail.com",
  "password": "938472829",
  "nickname": " updateprueba"
}



###  DELETE http://localhost:8000/api/users/delete/:id 



DELETE http://localhost:8000/api/users/delete/6


### host remoto

### Login POST https://api-gout.herokuapp.com/api/users/register Content-Type: application/json

POST https://api-gout.herokuapp.com/api/users/register 
Content-Type: application/json

{
  "username": "prueba2",
  "email": "prueba2@gmail.com",
  "password": "123456789",
  "nickname": "prueba2"
}

### Login POST https://api-gout.herokuapp.com/api/users/login Content-Type: application/json
POST https://api-gout.herokuapp.com/api/users/login 
Content-Type: application/json

{
  "email": "cristianpalocseres@gmail.com",
  "password": "123456789"
}


### users GET https://api-gout.herokuapp.com/api/users Content-Type: application/json



GET https://api-gout.herokuapp.com/api/users


